// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX1ELVokOIq5SS4T6JwKDNHpSFrq62Pnw',
    appId: '1:964493204164:web:3a1b79b53bd6099cb4c791',
    messagingSenderId: '964493204164',
    projectId: 'jobportel-1e3e7',
    authDomain: 'jobportel-1e3e7.firebaseapp.com',
    storageBucket: 'jobportel-1e3e7.firebasestorage.app',
    measurementId: 'G-P31TYLBJC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLES5QPLy2tO96lEyZ5yTIRQctye1Nnw',
    appId: '1:964493204164:android:a99c3fafb94553f7b4c791',
    messagingSenderId: '964493204164',
    projectId: 'jobportel-1e3e7',
    storageBucket: 'jobportel-1e3e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIMpKGDxjlnh9Bv8sG1owmNTiwYLqeoo8',
    appId: '1:964493204164:ios:c133ce6d7673f4d6b4c791',
    messagingSenderId: '964493204164',
    projectId: 'jobportel-1e3e7',
    storageBucket: 'jobportel-1e3e7.firebasestorage.app',
    iosBundleId: 'com.example.jobPortelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIMpKGDxjlnh9Bv8sG1owmNTiwYLqeoo8',
    appId: '1:964493204164:ios:c133ce6d7673f4d6b4c791',
    messagingSenderId: '964493204164',
    projectId: 'jobportel-1e3e7',
    storageBucket: 'jobportel-1e3e7.firebasestorage.app',
    iosBundleId: 'com.example.jobPortelApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX1ELVokOIq5SS4T6JwKDNHpSFrq62Pnw',
    appId: '1:964493204164:web:e4aee22cc2796c1eb4c791',
    messagingSenderId: '964493204164',
    projectId: 'jobportel-1e3e7',
    authDomain: 'jobportel-1e3e7.firebaseapp.com',
    storageBucket: 'jobportel-1e3e7.firebasestorage.app',
    measurementId: 'G-BM0RDY61GR',
  );
}
